<div class="page-header com-info">
          <div class="header grid">
               <div class="logo"><div></div><a class="full" href="index.html"></a></div>
               <ul class="menu">
                   <!--<li><span class="service"></span><span>提供服务</span><a class="full" href="http://ruanshan.com/index.html"></a></li>-->
                   <li><span class="case"></span><span>成功案例</span><a class="full" href="http://ruanshan.com/cases.html"></a></li>
                   <li  class="selected this" ><span class="h5share"></span><span>H5案例分享</span><a class="full" href="http://h5cases.ruanshan.com/" target="_blank"></a></li>
                   <li><span class="h5ketang"></span><span>H5课堂</span><a class="full" href="http://ruanshan.com/posts.html"  ></a></li>
                   <li ><span class="about"></span><span>关于软山</span><a class="full" href="http://ruanshan.com/about-us.html"></a></li>
               </ul>
          </div>
</div>
